language: node_js
node_js:
  - "7"
cache:
  directories:
    - node_modules
install: npm install
script:
  - bash ./deploy/deploy.sh
env:
  global:
    - COMMIT_AUTHOR_EMAIL: "dsevilla192@icloud.com"
dist: trusty
sudo: false
